# CodeGrey SOC - Unified Configuration (YAML)

server:
  host: 0.0.0.0
  port: 8443
  debug: false
  secret_key: your-super-secure-production-key
  log_level: INFO
  log_file: logs/soc_server.log

# Database (PostgreSQL recommended for production)
database:
  type: postgresql
  host: db-server
  port: 5432
  name: codegrey_soc
  user: soc_user
  password: secret

# S3/Cloud Storage
s3:
  bucket: your-soc-bucket
  region: us-east-1
  golden_image_bucket: your-soc-bucket-golden
  logs_bucket: your-soc-bucket-logs

# LLM/AI Reasoning - Local cybersec-ai Primary
llm:
  provider: ollama
  ollama_endpoint: http://localhost:11434
  ollama_model: cybersec-ai
  openai_api_key: sk-...
  openai_model: gpt-4o
  fallback_order:
    - ollama
    - openai
  timeout_seconds: 30
  temperature: 0.7
  max_tokens: 2048

# Attack Agent
attack:
  enable_real_attacks: true
  reroute_outgoing_traffic: true
  traffic_reroute_server: http://your-server:8080
  allow_element_override: true
  golden_image_required: true

# Golden Image Management
golden_image:
  method: auto
  storage: s3
  s3_bucket: your-soc-bucket-golden
  allow_user_upload: true
  restore_on_attack_complete: true

# Detection Agent
detection:
  ml_enabled: true
  ai_enabled: true
  ollama_enabled: true
  openai_fallback: true
  false_positive_tolerance: high
  false_negative_tolerance: low
  retrain_interval_hours: 24

# Multi-tenant
multi_tenant:
  max_agents_per_tenant: 1000
  max_commands_per_minute: 100

# Misc
api_rate_limit: 1000 per hour
